[package]
name = "ldap3_server"
version = "0.1.1"
authors = ["William Brown <william@blackhats.net.au>"]
edition = "2018"

description = "LDAP Server Codec for Tokio"
repository = "https://github.com/kanidm/ldap3_server"
readme = "README.md"
keywords = ["ldap", "authentication"]
categories = ["authentication"]
license = "MPL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lber = "0.2"
tokio-util = { version = "0.3", features = ["codec"] }
bytes = "0.5"

[dev-dependencies]
env_logger = "0.7"
log = "0.4"

futures-util = "0.3"
tokio = { version = "0.2", features=["full"] }
futures = "0.3"

# actix-rt = "1.0"
# actix_derive = "0.5"
# actix = "0.9"
